import { useEffect } from "react";
import { itemsAction } from "../store/itemSlice";
import { useDispatch, useSelector } from "react-redux";
import { fetchingStatusAction } from "../store/fetchingStatus";
const FetchItem = () => {
  const itemslist = {
    items: [
      {
        id: "001",
        image: "images/1.jpg",
        company: "Carlton London",
        item_name: "Rhodium-Plated CZ Floral Studs",
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.5, count: 1400 },
      },
      {
        id: "002",
        image: "images/2.jpg",
        company: "CUKOO",
        item_name: "Women Padded Halter Neck Swimming Dress",
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.3, count: 24 },
      },
      {
        id: "003",
        image: "images/3.jpg",
        company: "NUEVOSDAMAS",
        item_name: "Women Red & White Printed A-Line Knee-Length Skirts",
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.1, count: 249 },
      },
      {
        id: "004",
        image: "images/4.jpg",
        company: "ADIDAS",
        item_name: "Indian Cricket ODI Jersey",
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 5, count: 10 },
      },
      {
        id: "005",
        image: "images/5.jpg",
        company: "Roadster",
        item_name: "Pure Cotton T-shirt",
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.2, count: 3500 },
      },
      {
        id: "006",
        image: "images/6.jpg",
        company: "Nike",
        item_name: "Men ReactX Running Shoes",
        original_price: 14995,
        current_price: 14995,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 0, count: 0 },
      },
      {
        id: "007",
        image: "images/7.jpg",
        company: "The Indian Garage Co",
        item_name: "Men Slim Fit Regular Shorts",
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        rating: { stars: 4.2, count: 388 },
      },
      {
        id: "008",
        image: "images/8.jpg",
        company: "Nivea",
        item_name: "Men Fresh Deodrant 150ml",
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.2, count: 5200 },
      },
      {
        id: "009",
        image: "images/1.jpg",
        company: "Carlton London",
        item_name: "Rhodium-Plated CZ Floral Studs",
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.5, count: 1400 },
      },
      {
        id: "010",
        image: "images/2.jpg",
        company: "CUKOO",
        item_name: "Women Padded Halter Neck Swimming Dress",
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.3, count: 24 },
      },
      {
        id: "011",
        image: "images/3.jpg",
        company: "NUEVOSDAMAS",
        item_name: "Women Red & White Printed A-Line Knee-Length Skirts",
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.1, count: 249 },
      },
      {
        id: "012",
        image: "images/4.jpg",
        company: "ADIDAS",
        item_name: "Indian Cricket ODI Jersey",
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 5, count: 10 },
      },
      {
        id: "013",
        image: "images/5.jpg",
        company: "Roadster",
        item_name: "Pure Cotton T-shirt",
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.2, count: 3500 },
      },
      {
        id: "014",
        image: "images/6.jpg",
        company: "Nike",
        item_name: "Men ReactX Running Shoes",
        original_price: 14995,
        current_price: 14995,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 0, count: 0 },
      },
      {
        id: "015",
        image: "images/7.jpg",
        company: "The Indian Garage Co",
        item_name: "Men Slim Fit Regular Shorts",
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        rating: { stars: 4.2, count: 388 },
      },
      {
        id: "016",
        image: "images/8.jpg",
        company: "Nivea",
        item_name: "Men Fresh Deodrant 150ml",
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.2, count: 5200 },
      },
      {
        id: "017",
        image: "images/1.jpg",
        company: "Carlton London",
        item_name: "Rhodium-Plated CZ Floral Studs",
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.5, count: 1400 },
      },
      {
        id: "018",
        image: "images/2.jpg",
        company: "CUKOO",
        item_name: "Women Padded Halter Neck Swimming Dress",
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.3, count: 24 },
      },
      {
        id: "019",
        image: "images/3.jpg",
        company: "NUEVOSDAMAS",
        item_name: "Women Red & White Printed A-Line Knee-Length Skirts",
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.1, count: 249 },
      },
      {
        id: "020",
        image: "images/4.jpg",
        company: "ADIDAS",
        item_name: "Indian Cricket ODI Jersey",
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 5, count: 10 },
      },
      {
        id: "021",
        image: "images/5.jpg",
        company: "Roadster",
        item_name: "Pure Cotton T-shirt",
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.2, count: 3500 },
      },
      {
        id: "022",
        image: "images/6.jpg",
        company: "Nike",
        item_name: "Men ReactX Running Shoes",
        original_price: 14995,
        current_price: 14995,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 0, count: 0 },
      },
      {
        id: "023",
        image: "images/7.jpg",
        company: "The Indian Garage Co",
        item_name: "Men Slim Fit Regular Shorts",
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        rating: { stars: 4.2, count: 388 },
      },
      {
        id: "024",
        image: "images/8.jpg",
        company: "Nivea",
        item_name: "Men Fresh Deodrant 150ml",
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.2, count: 5200 },
      },
      {
        id: "025",
        image: "images/1.jpg",
        company: "Carlton London",
        item_name: "Rhodium-Plated CZ Floral Studs",
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.5, count: 1400 },
      },
      {
        id: "026",
        image: "images/2.jpg",
        company: "CUKOO",
        item_name: "Women Padded Halter Neck Swimming Dress",
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.3, count: 24 },
      },
      {
        id: "027",
        image: "images/3.jpg",
        company: "NUEVOSDAMAS",
        item_name: "Women Red & White Printed A-Line Knee-Length Skirts",
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.1, count: 249 },
      },
      {
        id: "028",
        image: "images/4.jpg",
        company: "ADIDAS",
        item_name: "Indian Cricket ODI Jersey",
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 5, count: 10 },
      },
      {
        id: "029",
        image: "images/5.jpg",
        company: "Roadster",
        item_name: "Pure Cotton T-shirt",
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.2, count: 3500 },
      },
      {
        id: "030",
        image: "images/6.jpg",
        company: "Nike",
        item_name: "Men ReactX Running Shoes",
        original_price: 14995,
        current_price: 14995,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 0, count: 0 },
      },
      {
        id: "031",
        image: "images/7.jpg",
        company: "The Indian Garage Co",
        item_name: "Men Slim Fit Regular Shorts",
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        rating: { stars: 4.2, count: 388 },
      },
      {
        id: "032",
        image: "images/8.jpg",
        company: "Nivea",
        item_name: "Men Fresh Deodrant 150ml",
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: "10 Oct 2023",
        rating: { stars: 4.2, count: 5200 },
      },
    ],
  };

  const fetchingStatus = useSelector((store) => store.fetchingStatus);

  // console.log(fetchingStatus)
  const dispatch = useDispatch();

  useEffect(() => {
    if (fetchingStatus.markFetchDone) return;

    const controller = new AbortController();
    const signal = controller.signal;

    dispatch(fetchingStatusAction.fetchingStarted());
    dispatch(fetchingStatusAction.markFetchDone());
    dispatch(itemsAction.addInitialValue(itemslist.items));

    // fetch("http://localhost:8080/items", { signal })
    //   .then((res) => res.json())
    //   .then(({ items }) => {
    //     dispatch(fetchingStatusAction.markFetchDone());

    //     dispatch(itemsAction.addInitialValue(items));
    //   });

    return () => {
      // controller.abort();
    };
  }, [fetchingStatus]);

  // console.log(fetchingStatus)

  return;
};

export default FetchItem;
